### ISSUE TITLE
Antialiasing / MSAA / FXAA implementation

### ISSUE THREAD

**Issue by Sakul6499** [Sakul6499/WGPU-Engine#44]
Add some kind of Antialiasing support

**Comment by Sakul6499** [comment]
[smaa](https://crates.io/crates/smaa) sounds promising

**Comment by Sakul6499** [comment]
Antialiasing is a complicated topic and requires more research.
Help wanted! :)

**Comment by SakulFlee** [comment]
Project support dropped / Archived
