### ISSUE TITLE
Split project into multiple sub-crates

### ISSUE THREAD

**Issue by Sakul6499** [Sakul6499/WGPU-Engine#7]
Currently, everything is thrown together into one monolithic crate.

After this issue, everything should be spaced out into its own crate.
This also would allow for a more "Build your own Engine" approach, where someone may only want the Engine part, others want the whole ECS system, etc.

Additionally, the "game part" should be either moved out, or into an example.

Ultimately, the split look like this:

- `crates/abstract_engine`
- `crates/wgpu_engine`
- `crates/framework`
- `crates/app`
- `crates/input_handler`
- `crates/camera`
- `crates/instance`
- `crates/material`
- `crates/mesh`
- `crates/texture`
- `crates/vertex`
- `crates/gltf`
- `crates/world_gen`
- `examples/triangle`
- `examples/square`
- `examples/ecs`
- `examples/cheese`
- `examples/world_gen`

**Comment by SakulFlee** [comment]
Project support dropped / Archived
